"use client";

import { Tabs, TabsContent, TabsList, TabsTrigger } from "@/components/ui/tabs";
import { CustomerDocumentUpload } from "@/app/components/customer-document-upload";
import { CustomerPaymentReceiptUpload } from "@/app/components/customer-payment-receipt-upload";
import { ShipmentLocationMap } from "@/app/components/shipment-location-map";
import { CheckCircle2, Download, FileDown, FileText, MapPin, Ship } from "lucide-react";

type Order = { id:string; orderNo:string|null; totalAmountMnt:number; depositAmountMnt:number; balanceAmountMnt:number; status:string };
type Estimate = { vehiclePriceKrw:number; purchaseFeeKrw:number; inlandTransportKrw:number; oceanFreightUsd:number; customsMnt:number; vatMnt:number; otherCostsMnt:number; totalMnt:number; updatedAt:string };
type Payment = { id:string; paymentType:string; currency:string; amount:number; amountMnt:number; status:string; dueDate:string|null; paidAt:string|null };
type Document = { id:string; documentType:string; fileName:string; status:string; sizeBytes:number; createdAt:string; paymentId:string|null };
type Shipment = { originPort:string|null; destination:string|null; currentLocation:string|null; status:string; estimatedArrival:string|null };
type Event = { id:string; eventCode:string; location:string|null; note:string|null; eventAt:string };
const money=new Intl.NumberFormat("mn-MN",{maximumFractionDigits:0});
const documentTypeLabels:Record<string,string>={INVOICE:"Нэхэмжлэх",EXPORT_CERTIFICATE:"Экспортын гэрчилгээ",BILL_OF_LADING:"Тээврийн коносамент (B/L)",CUSTOMS:"Гаалийн баримт",VEHICLE_REGISTRATION:"Автомашины гэрчилгээ",CONTRACT:"Гэрээ",OTHER:"Бусад баримт",PAYMENT_RECEIPT:"Төлбөрийн баримт"};

export function VehicleDetailTabs({order,estimate,payments,documents,shipment,events}:{order:Order;estimate:Estimate|null;payments:Payment[];documents:Document[];shipment:Shipment|null;events:Event[]}) {
  const paid=payments.filter(item=>item.status==="PAID").reduce((sum,item)=>sum+item.amountMnt,0);
  const depositPaid=payments.filter(item=>item.paymentType==="DEPOSIT"&&item.status==="PAID").reduce((sum,item)=>sum+item.amountMnt,0);
  const depositStatus=order.depositAmountMnt<=0?"Барьцаа шаардлагагүй":depositPaid>=order.depositAmountMnt?"Төлөгдсөн":depositPaid>0?"Хэсэгчлэн төлсөн":"Төлөөгүй";
  const depositClass=depositStatus==="Төлөгдсөн"?"paid":depositStatus==="Хэсэгчлэн төлсөн"?"partial":"pending";
  const today=new Date().toISOString().slice(0,10);
  return <Tabs defaultValue="cost" className="vehicle-tabs"><TabsList variant="line" className="vehicle-tabs-list"><TabsTrigger value="cost">Үнийн тооцоо</TabsTrigger><TabsTrigger value="payment">Төлбөр</TabsTrigger><TabsTrigger value="documents">Бичиг баримт</TabsTrigger><TabsTrigger value="shipping">Тээврийн явц</TabsTrigger></TabsList>
    <TabsContent value="cost" className="tab-panel">{estimate?<div className="cost-grid"><div className="cost-lines"><div><span>Автомашины үнэ</span><strong>{money.format(estimate.vehiclePriceKrw)} KRW</strong></div><div><span>Солонгос дахь зардал</span><strong>{money.format(estimate.purchaseFeeKrw+estimate.inlandTransportKrw)} KRW</strong></div><div><span>Олон улсын тээвэр</span><strong>{money.format(estimate.oceanFreightUsd)} USD</strong></div><div><span>Гааль, НӨАТ</span><strong>{money.format(estimate.customsMnt+estimate.vatMnt)} ₮</strong></div><div><span>Бусад зардал</span><strong>{money.format(estimate.otherCostsMnt)} ₮</strong></div></div><div className="cost-total"><span>МОНГОЛД БУУХ НИЙТ ҮНЭ</span><strong>{money.format(order.totalAmountMnt)} ₮</strong><small>{estimate.updatedAt.slice(0,10)}-ны тооцоо</small></div></div>:<div className="panel-empty">Үнийн дэлгэрэнгүй тооцоо олдсонгүй.</div>}</TabsContent>
    <TabsContent value="payment" className="tab-panel"><div className="payment-summary"><div><span>Нийт төлсөн</span><strong>{money.format(paid)} ₮</strong></div><div><span>Урьдчилгаа · суурь дүнгийн 30%</span><strong className={`deposit-state ${depositClass}`}>{depositStatus}</strong><small>{money.format(depositPaid)} / {money.format(order.depositAmountMnt)} ₮</small></div><div><span>Машины үлдэгдэл · 70%</span><strong>{money.format(order.balanceAmountMnt)} ₮</strong></div></div>{payments.some(item=>item.status==="PENDING"&&!!item.dueDate&&item.dueDate<today)&&<div className="payment-overdue-banner">Хугацаа хэтэрсэн төлбөр байна. Төлбөрийн дэлгэрэнгүйг шалгана уу.</div>}<CustomerPaymentReceiptUpload orderId={order.id}/><div className="customer-invoice-action"><a className="document-download-link" href={`/portal/vehicles/${encodeURIComponent(order.orderNo ?? order.id)}/invoice`}><FileDown/> Нэхэмжлэх татах / хэвлэх</a></div>{payments.length?payments.map(item=><div className="document-row" key={item.id}><FileText size={18}/><span><strong>{item.paymentType}</strong><small>{item.paidAt??"Төлбөр хүлээгдэж байна"}</small>{item.dueDate&&<small className={item.status==="PENDING"&&item.dueDate<today?"payment-overdue-text":"payment-due-text"}>Төлөх хугацаа: {item.dueDate}{item.status==="PENDING"&&item.dueDate<today?" · Хугацаа хэтэрсэн":""}</small>}</span><b>{money.format(item.amount)} {item.currency}{item.currency!=="MNT"&&<small className="payment-mnt-equivalent">≈ {money.format(item.amountMnt)} ₮</small>}</b><em className={`record-status ${item.status==="PENDING"&&item.dueDate&&item.dueDate<today?"overdue":""}`}>{item.status}</em></div>):<div className="panel-empty">Төлбөрийн гүйлгээ бүртгэгдээгүй.</div>}</TabsContent>
    <TabsContent value="documents" className="tab-panel"><CustomerDocumentUpload orderId={order.id}/><div className="document-actions"><h3>Автомашины бичиг баримт</h3><small>Таны илгээсэн файлыг админ шалгасны дараа татах боломжтой.</small></div>{documents.length?documents.map(item=><div className="document-row" key={item.id}><FileText size={18}/><span><strong>{item.fileName}</strong><small>{documentTypeLabels[item.documentType]??item.documentType} · {Math.max(1,Math.round(item.sizeBytes/1024))} KB · {item.createdAt.slice(0,10)}</small></span><b className={item.status.toLowerCase()}>{item.status === "VERIFIED" ? "БАТАЛГААЖСАН" : item.status === "REJECTED" ? "ТАТГАЛЗСАН" : "ШАЛГАЖ БАЙНА"}</b>{item.status === "VERIFIED" && <ButtonDownload documentId={item.id}/>}</div>):<div className="panel-empty">Бичиг баримт хараахан хавсаргаагүй байна.</div>}</TabsContent>
    <TabsContent value="shipping" className="tab-panel">{shipment?<><div className="shipping-route"><span><MapPin size={18}/><small>Эхлэх цэг</small><strong>{shipment.originPort??"БНСУ"}</strong></span><i>→</i><span><Ship size={18}/><small>Одоогийн байршил</small><strong>{shipment.currentLocation??"Бэлтгэл шат"}</strong></span><i>→</i><span><MapPin size={18}/><small>Тооцоолсон ирэх</small><strong>{shipment.estimatedArrival??"Тодорхойгүй"}</strong></span></div><ShipmentLocationMap origin={shipment.originPort} location={shipment.currentLocation} destination={shipment.destination}/><div className="full-timeline dynamic">{events.map(item=><div className="done" key={item.id}><i><CheckCircle2 size={13}/></i><span><strong>{item.note??item.eventCode}</strong><small>{item.location??""} {item.eventAt}</small></span></div>)}</div></>:<div className="panel-empty">Тээврийн мэдээлэл хараахан үүсээгүй.</div>}</TabsContent>
  </Tabs>;
}

function ButtonDownload({documentId}:{documentId:string}) {
  return <a className="document-download-link" href={`/api/documents/${encodeURIComponent(documentId)}`}><Download/> Татах</a>;
}
