import { getNetlifyBucket } from "@/lib/netlify-bucket";

export const expoRegions=["ASIA","EUROPE","AMERICAS","OTHER"] as const;
function text(formData:FormData,key:string,max:number,required=false){const value=String(formData.get(key)??"").trim();if((required&&!value)||value.length>max)throw new Error("INVALID_TEXT");return value||null;}
function dateValue(formData:FormData,key:string,required=false){const value=String(formData.get(key)??"").trim();if(!value&&!required)return null;if(!/^\d{4}-\d{2}-\d{2}$/.test(value))throw new Error("INVALID_DATE");return value;}
function urlValue(formData:FormData,key:string){const value=String(formData.get(key)??"").trim();if(!value)return null;const url=new URL(value);if(!/^https?:$/.test(url.protocol))throw new Error("INVALID_URL");return url.toString();}
export function normalizeExpoForm(formData:FormData){const startDate=dateValue(formData,"startDate",true)!;const endDate=dateValue(formData,"endDate",true)!;if(startDate>endDate)throw new Error("INVALID_DATE_RANGE");const registrationDeadline=dateValue(formData,"registrationDeadline");const region=String(formData.get("region")??"ASIA") as typeof expoRegions[number];if(!expoRegions.includes(region))throw new Error("INVALID_REGION");return{title:text(formData,"title",200,true)!,country:text(formData,"country",100,true)!,city:text(formData,"city",100,true)!,venue:text(formData,"venue",180),startDate,endDate,officialUrl:urlValue(formData,"officialUrl"),videoUrl:urlValue(formData,"videoUrl"),region,category:text(formData,"category",180),description:text(formData,"description",1500),registrationDeadline,ticketInfo:text(formData,"ticketInfo",800),participationTerms:text(formData,"participationTerms",1200),imageUrl:urlValue(formData,"imageUrl"),isFeatured:formData.get("isFeatured")==="true",isPublished:formData.get("isPublished")==="true"};}
export function getExpoBucket(){return getNetlifyBucket();}
export async function storeExpoImage(expoId:string,file:File){const extension=file.name.split(".").pop()?.toLowerCase()??"";if(!new Set(["image/jpeg","image/png","image/webp"]).has(file.type)||!["jpg","jpeg","png","webp"].includes(extension)||file.size<=0||file.size>5*1024*1024)throw new Error("INVALID_IMAGE");const objectKey=`expo-images/${expoId}/${crypto.randomUUID()}.${extension}`;await getExpoBucket().put(objectKey,file.stream(),{httpMetadata:{contentType:file.type}});return objectKey;}
